#ifndef SDB_H_INCLUDED
#define SDB_H_INCLUDED
typedef unsigned long int uint8 ;
bool SDB_isFull (void); // tmm ......................................
uint8 SDB_GetUsedSize (void); // tmm ..................................
bool SDB_AddEntry (uint8 id,uint8 years,uint8*subjects,uint8*grades); //tmm .....................................
void SDB_DeleteEntry (uint8 id);
bool SDB_ReadEntry (uint8 id,uint8*years,uint8*subjects,uint8*grades); // tmm ........................................
void SDB_GetIdList(uint8*count,uint8*list);
bool SDB_IsIdExist(uint8 id); // tmm .................................

void AddInbeginning (uint8 id,uint8 years,uint8*subjects,uint8*grades);// tmm .............................
void AddAtEnd (uint8 id,uint8 years,uint8*subjects,uint8*grades);// tmm ..............................


#endif // SDB_H_INCLUDED
